"""
PHASE 0: Contract for course outline output.

This is what agents produce. Standard schema for all downstream consumers (UI, exports, validator).

Reference: https://architecture.md -> Module / Outline schema section
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from enum import Enum


class BloomLevel(str, Enum):
    """Bloom's taxonomy cognitive levels."""
    REMEMBER = "remember"
    UNDERSTAND = "understand"
    APPLY = "apply"
    ANALYZE = "analyze"
    EVALUATE = "evaluate"
    CREATE = "create"


class LearningObjective(BaseModel):
    """
    Single measurable learning outcome.
    
    Follows "BLOOM_VERB + Measurable Metric" pattern.
    e.g., "Implement a decision tree classifier using scikit-learn"
    """
    
    objective_id: str = Field(..., description="e.g., 'LO_1_1', 'LO_2_3'")
    statement: str = Field(..., description="'Verb + measurable outcome'")
    bloom_level: BloomLevel = Field(..., description="Cognitive level")
    assessment_method: str = Field(..., description="How it's assessed (e.g., 'Lab submission')")


class Lesson(BaseModel):
    """Single lesson within a module."""
    
    lesson_id: str = Field(..., description="e.g., 'L_1_1'")
    title: str
    duration_minutes: int = Field(..., ge=15)
    activities: List[str] = Field(default_factory=list, description="Activities in this lesson")
    assessment_type: Optional[str] = Field(None, description="e.g., 'Quiz', 'Hands-on', 'Discussion'")
    resources: List[Dict[str, str]] = Field(
        default_factory=list, 
        description="[{'title': '...', 'url': '...', 'type': 'video|reading|tool'}]"
    )


class Module(BaseModel):
    """Single course module."""
    
    module_id: str = Field(..., description="e.g., 'M_1'")
    title: str
    synopsis: str = Field(..., description="2–3 sentence overview")
    estimated_hours: float
    learning_objectives: List[LearningObjective] = Field(..., min_items=3, max_items=7)
    lessons: List[Lesson] = Field(..., description="Ordered list of lessons")
    assessment: Dict[str, Any] = Field(
        default_factory=dict, 
        description="{'type': 'quiz|project|exam', 'weight': 0.1, 'rubric': '...'}"
    )
    bloom_level: BloomLevel = Field(..., description="Highest Bloom level in this module")
    keywords: List[str] = Field(default_factory=list, description="Key terms covered")
    readings_and_resources: List[Dict[str, str]] = Field(
        default_factory=list, 
        description="[{'title': '...', 'url': '...', 'source': 'web|retrieved|uploaded', 'confidence': 0.9}]"
    )


class CourseOutlineSchema(BaseModel):
    """
    Complete course outline generated by Module Creation Agent.
    
    This is the main output schema used by validator, UI, and exports.
    """
    
    # Metadata
    course_title: str
    course_summary: str = Field(..., description="2–3 sentence overview")
    audience_level: str
    audience_category: str
    learning_mode: str
    depth_requirement: str
    total_duration_hours: int
    
    # Outcome structure
    prerequisites: List[str] = Field(default_factory=list, description="Skills/concepts required")
    course_level_learning_outcomes: List[LearningObjective] = Field(
        ..., 
        description="Module-independent overall course goals"
    )
    
    # Modules
    modules: List[Module] = Field(..., min_items=2, description="Ordered list of modules")
    
    # Capstone / culminating activity
    capstone_project: Optional[Dict[str, Any]] = Field(
        None, 
        description="{'title': '...', 'scope': '...', 'deliverables': [...], 'rubric': {...}}"
    )
    
    # Assessment & evaluation
    evaluation_strategy: Dict[str, Any] = Field(
        default_factory=dict, 
        description="{'formative': [...], 'summative': [...], 'rubrics': {...}}"
    )
    
    # Tools & resources
    recommended_tools: List[str] = Field(default_factory=list)
    datasets_or_datasets_examples: List[Dict[str, str]] = Field(
        default_factory=list, 
        description="[{'name': '...', 'source': '...', 'size': '...'}]"
    )
    
    # Instructor support
    instructor_notes: Optional[str] = Field(
        None, 
        description="Pacing tips, inclusive design notes, etc."
    )
    
    # Provenance & citations
    citations_and_provenance: List[Dict[str, Any]] = Field(
        default_factory=list, 
        description="[{'source': 'web|retrieved|uploaded', 'url': '...', 'title': '...', 'confidence': 0.9}]"
    )
    
    # System metadata
    generated_by_agent: str = Field(default="module_creation_agent")
    generation_timestamp: Optional[str] = Field(None, description="ISO 8601 timestamp")


class ValidatorFeedbackSchema(BaseModel):
    """PHASE 6: Structured feedback from Validator Agent."""
    
    score: float = Field(..., ge=0, le=100, description="Numeric score out of 100")
    
    rubric_breakdown: Dict[str, float] = Field(
        ..., 
        description="{'coverage': 25, 'depth_alignment': 18, ...}"
    )
    
    accept: bool = Field(..., description="True if score >= threshold")
    
    feedback: List[str] = Field(
        default_factory=list, 
        description="Human-readable feedback for improvements"
    )
    
    targeted_edits: Optional[Dict[str, str]] = Field(
        None, 
        description="{'module_2_increase_examples': '...', 'add_assessment_for_lo_2_3': '...'}"
    )
    
    regenerate_modules: Optional[List[str]] = Field(
        None, 
        description="List of module IDs that need regeneration, e.g., ['M_2', 'M_5']"
    )
